services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "31102006" # Nên để trong ngoặc kép vì là chuỗi số
      POSTGRES_DB: docbooking
    ports:
      - "5439:5432" # Máy thật dùng 5439 để tránh trùng nếu máy bạn đã cài Postgres sẵn
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data: