spring.application.name=Backend
server.port=5020

spring.datasource.url=jdbc:postgresql://localhost:5432/Docbooking
spring.datasource.username=postgres
spring.datasource.password=31102006

# Ch? ki?m tra xem Entity có kh?p v?i Table không, KHÔNG s?a ??i Database
spring.jpa.hibernate.ddl-auto=validate