spring.application.name=Backend
server.port=5020

# --- DATABASE Configuration ---
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?pgbouncer=true&prepareThreshold=0
spring.datasource.username=postgres.jwxtmjpscfjpqtczpmyf
spring.datasource.password=docbookingtenpoint

# JPA Config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# --- CLOUDINARY Configuration ---
cloudinary.cloud-name=dw8jqem75
cloudinary.api-key=812978112674131
cloudinary.api-secret=2yawXiFeeatweikM0h8jGt65X3E

# Upload Size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# --- JWT Configuration ---
security.jwt.secret-key=RGF5TGFNb3RDb25EYXVTaWV1QmFvTWF0Q3VhSGVUaG9uZ0RvY0Jvb2tpbmdTaWV1Q2FwMjAyNk5oZQ==
security.jwt.expiration-time=86400000

# --- GMAIL Configuration ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=catashiro31@gmail.com
spring.mail.password=jgci xsqv bbpt kyex
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Ép kết nối hết hạn sau 1 phút (60000ms) để tạo cái mới, tránh bị DB ngắt trước
spring.datasource.hikari.max-lifetime=60000

# Nếu rảnh rỗi quá 30 giây (30000ms) thì dọn dẹp luôn
spring.datasource.hikari.idle-timeout=30000

# Cứ mỗi 30 giây gửi một tín hiệu nhỏ để DB biết "tôi vẫn đang dùng"
spring.datasource.hikari.keepalive-time=30000